// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

// LinkRequest defines model for LinkRequest.
type LinkRequest struct {
	// Link Ссылка
	Link string `json:"link"`
}

// OriginalLinkResponse defines model for OriginalLinkResponse.
type OriginalLinkResponse struct {
	Link *string `json:"link,omitempty"`
}

// ShortLinkResponse defines model for ShortLinkResponse.
type ShortLinkResponse struct {
	ShortLink *string `json:"short_link,omitempty"`
}

// GetOriginalLinkParams defines parameters for GetOriginalLink.
type GetOriginalLinkParams struct {
	Link string `form:"link" json:"link"`
}

// GetShortLinkParams defines parameters for GetShortLink.
type GetShortLinkParams struct {
	Link string `form:"link" json:"link"`
}

// AddLinkJSONRequestBody defines body for AddLink for application/json ContentType.
type AddLinkJSONRequestBody = LinkRequest
